name: Deploy Go Blog

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Go binary
        run: go build -o main

      - name: Sync files to server (using rsync + password)
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ubuntu@${{ secrets.SERVER_IP }}:/root/h_blog/
        env:
          RSYNC_PASSWORD: ${{ secrets.SERVER_PASSWORD }}

      - name: Restart service
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} \
            "cd /root/h_blog && sudo systemctl restart h_blog"
        env:
          SSH_PASSWORD: ${{ secrets.SERVER_PASSWORD }}