name: Deploy Blog

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Go binary
        run: go build -o main

      - name: Deploy to server
        run: |
          sshpass -p '${{ secrets.SERVER_PASSWORD }}' scp -o StrictHostKeyChecking=no \
            main content/ templates/ \
            root@${{ secrets.SERVER_IP }}:/root/h_blog/
          
          sshpass -p '${{ secrets.SERVER_PASSWORD }}' ssh -o StrictHostKeyChecking=no \
            root@${{ secrets.SERVER_IP }} "systemctl restart h_blog"