#name: Deploy Go Blog
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.19
#
#      - name: Build Go binary
#        run: |
#          go build -o main
#
#      - name: Install SSH key
#        uses: webfactory/ssh-agent@v0.5.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#
#      - name: Deploy to server
#        run: |
#          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} "cd ~/go-blog && git pull origin main && sudo systemctl restart go-blog"